[2023-08-24T20:49:16.932+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: your_first_dag.Create_txt_file manual__2023-08-24T20:49:12.187558+00:00 [queued]>
[2023-08-24T20:49:16.937+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: your_first_dag.Create_txt_file manual__2023-08-24T20:49:12.187558+00:00 [queued]>
[2023-08-24T20:49:16.938+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-24T20:49:16.944+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Create_txt_file> on 2023-08-24 20:49:12.187558+00:00
[2023-08-24T20:49:16.948+0000] {standard_task_runner.py:57} INFO - Started process 2393 to run task
[2023-08-24T20:49:16.951+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'your_first_dag', 'Create_txt_file', 'manual__2023-08-24T20:49:12.187558+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/1_first_dag/first_dag.py', '--cfg-path', '/tmp/tmp633b13b2']
[2023-08-24T20:49:16.952+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask Create_txt_file
[2023-08-24T20:49:16.988+0000] {task_command.py:415} INFO - Running <TaskInstance: your_first_dag.Create_txt_file manual__2023-08-24T20:49:12.187558+00:00 [running]> on host 4059ad9a5b0d
[2023-08-24T20:49:17.038+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Willis' AIRFLOW_CTX_DAG_ID='your_first_dag' AIRFLOW_CTX_TASK_ID='Create_txt_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T20:49:12.187558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T20:49:12.187558+00:00'
[2023-08-24T20:49:17.039+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-24T20:49:17.040+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "Ceci est un fichier test" > /opt/***/ddags/1_first_dag/sample.txt']
[2023-08-24T20:49:17.050+0000] {subprocess.py:86} INFO - Output:
[2023-08-24T20:49:17.052+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/ddags/1_first_dag/sample.txt: No such file or directory
[2023-08-24T20:49:17.052+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-24T20:49:17.063+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-24T20:49:17.065+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=your_first_dag, task_id=Create_txt_file, execution_date=20230824T204912, start_date=20230824T204916, end_date=20230824T204917
[2023-08-24T20:49:17.072+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task Create_txt_file (Bash command failed. The command returned a non-zero exit code 1.; 2393)
[2023-08-24T20:49:17.083+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-24T20:49:17.097+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
