[2023-08-09T03:46:55.814+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow_dag.create_txt_file scheduled__2023-08-08T00:00:00+00:00 [queued]>
[2023-08-09T03:46:55.821+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow_dag.create_txt_file scheduled__2023-08-08T00:00:00+00:00 [queued]>
[2023-08-09T03:46:55.821+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-09T03:46:55.830+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): create_txt_file> on 2023-08-08 00:00:00+00:00
[2023-08-09T03:46:55.834+0000] {standard_task_runner.py:57} INFO - Started process 6011 to run task
[2023-08-09T03:46:55.838+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'taskflow_dag', 'create_txt_file', 'scheduled__2023-08-08T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/5_taskflow_api/taskflowoo.py', '--cfg-path', '/tmp/tmpckpxdzrp']
[2023-08-09T03:46:55.839+0000] {standard_task_runner.py:85} INFO - Job 75: Subtask create_txt_file
[2023-08-09T03:46:55.893+0000] {task_command.py:410} INFO - Running <TaskInstance: taskflow_dag.create_txt_file scheduled__2023-08-08T00:00:00+00:00 [running]> on host ce583f477705
[2023-08-09T03:46:55.962+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Willis' AIRFLOW_CTX_DAG_ID='taskflow_dag' AIRFLOW_CTX_TASK_ID='create_txt_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-08T00:00:00+00:00'
[2023-08-09T03:46:55.966+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/5_taskflow_api/taskflowoo.py", line 45, in create_txt_file
    with open('/opt/airflow/dags/5_taskflow/sample_taskflow.txt', 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/5_taskflow/sample_taskflow.txt'
[2023-08-09T03:46:55.990+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=taskflow_dag, task_id=create_txt_file, execution_date=20230808T000000, start_date=20230809T034655, end_date=20230809T034655
[2023-08-09T03:46:55.998+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 75 for task create_txt_file ([Errno 2] No such file or directory: '/opt/airflow/dags/5_taskflow/sample_taskflow.txt'; 6011)
[2023-08-09T03:46:56.010+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-09T03:46:56.026+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-09T04:35:34.821+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow_dag.create_txt_file scheduled__2023-08-08T00:00:00+00:00 [queued]>
[2023-08-09T04:35:34.827+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow_dag.create_txt_file scheduled__2023-08-08T00:00:00+00:00 [queued]>
[2023-08-09T04:35:34.828+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-09T04:35:34.837+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): create_txt_file> on 2023-08-08 00:00:00+00:00
[2023-08-09T04:35:34.842+0000] {standard_task_runner.py:57} INFO - Started process 6905 to run task
[2023-08-09T04:35:34.847+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'taskflow_dag', 'create_txt_file', 'scheduled__2023-08-08T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/5_taskflow_api/taskflow_dag.py', '--cfg-path', '/tmp/tmpg5rv8u46']
[2023-08-09T04:35:34.849+0000] {standard_task_runner.py:85} INFO - Job 93: Subtask create_txt_file
[2023-08-09T04:35:34.937+0000] {task_command.py:410} INFO - Running <TaskInstance: taskflow_dag.create_txt_file scheduled__2023-08-08T00:00:00+00:00 [running]> on host ce583f477705
[2023-08-09T04:35:35.021+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Willis' AIRFLOW_CTX_DAG_ID='taskflow_dag' AIRFLOW_CTX_TASK_ID='create_txt_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-08T00:00:00+00:00'
[2023-08-09T04:35:35.025+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-09T04:35:35.037+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=taskflow_dag, task_id=create_txt_file, execution_date=20230808T000000, start_date=20230809T043534, end_date=20230809T043535
[2023-08-09T04:35:35.057+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-09T04:35:35.073+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
