[2023-08-25T00:40:46.730+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: your_first_dag.Create_txt_file scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-08-25T00:40:46.736+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: your_first_dag.Create_txt_file scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-08-25T00:40:46.736+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-25T00:40:46.742+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Create_txt_file> on 2023-08-24 00:00:00+00:00
[2023-08-25T00:40:46.746+0000] {standard_task_runner.py:57} INFO - Started process 2608 to run task
[2023-08-25T00:40:46.749+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'your_first_dag', 'Create_txt_file', 'scheduled__2023-08-24T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/1_first_dag/first_dag.py', '--cfg-path', '/tmp/tmpas54sl1h']
[2023-08-25T00:40:46.751+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask Create_txt_file
[2023-08-25T00:40:46.787+0000] {task_command.py:415} INFO - Running <TaskInstance: your_first_dag.Create_txt_file scheduled__2023-08-24T00:00:00+00:00 [running]> on host 4059ad9a5b0d
[2023-08-25T00:40:46.837+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Willis' AIRFLOW_CTX_DAG_ID='your_first_dag' AIRFLOW_CTX_TASK_ID='Create_txt_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-24T00:00:00+00:00'
[2023-08-25T00:40:46.840+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-25T00:40:46.841+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "Ceci est un fichier test" > /opt/***/ddags/1_first_dag/sample.txt']
[2023-08-25T00:40:46.850+0000] {subprocess.py:86} INFO - Output:
[2023-08-25T00:40:46.852+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/ddags/1_first_dag/sample.txt: No such file or directory
[2023-08-25T00:40:46.853+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-25T00:40:46.863+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-25T00:40:46.865+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=your_first_dag, task_id=Create_txt_file, execution_date=20230824T000000, start_date=20230825T004046, end_date=20230825T004046
[2023-08-25T00:40:46.872+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task Create_txt_file (Bash command failed. The command returned a non-zero exit code 1.; 2608)
[2023-08-25T00:40:46.882+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-25T00:40:46.895+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
